# External data collection- Dubrovnik weather data

This notebook retrieves historical hourly weather data for Dubrovnik, Croatia from year 2024 to 2025.

Source: Open-Mateo.com API

Output: CSV file stored to 'uber_driver_project/data/raw/weather_hourly_2024_2025.csv'

## Importing libraries

In [2]:
import requests
import pandas as pd

#### Dubrovnik coordinates

In [3]:
latitude = 42.6481
longitude = 18.0922

## Configuration

In [4]:
url = 'https://archive-api.open-meteo.com/v1/archive'

In [5]:
params = {
    'latitude':42.6481,
    'longitude':18.0922,
    'start_date':'2024-04-19',
    'end_date':'2025-08-29',
    'hourly':'temperature_2m,precipitation,weathercode,apparent_temperature'
}

## API request

In [6]:
response = requests.get(url,params=params)

In [7]:
data = response.json()

## Convert JSON to Dataframe

In [8]:
hourly_data = data['hourly']
df_weather = pd.DataFrame(hourly_data)
df_weather.head()

,time,temperature_2m,precipitation,weathercode,apparent_temperature
0,2024-04-19T00:00,8.5,0.0,1,6.2
1,2024-04-19T01:00,8.9,0.0,3,6.4
2,2024-04-19T02:00,9.2,0.0,3,5.8
3,2024-04-19T03:00,8.3,0.0,3,4.9
4,2024-04-19T04:00,8.2,0.0,3,4.7

In [9]:
df_weather.tail()

,time,temperature_2m,precipitation,weathercode,apparent_temperature
11947,2025-08-29T19:00,24.8,0.3,51,24.7
11948,2025-08-29T20:00,24.4,0.1,51,24.4
11949,2025-08-29T21:00,23.4,0.2,51,24.2
11950,2025-08-29T22:00,23.3,0.0,2,23.5
11951,2025-08-29T23:00,22.5,2.5,63,24.2

## Save DataFrame to CSV file

In [10]:
df_weather.to_csv('../data/raw_data/weather_hourly_2024_2025.csv', index = False)